# Generated by Django 4.2.2 on 2023-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('url', models.URLField()),
                ('brand', models.CharField(max_length=50)),
                ('sale_price', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('00', '00:00'), ('10', '10:00'), ('14', '14:00'), ('18', '18:00')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
