# Generated by Django 4.1.3 on 2022-11-14 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muearly', '0002_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(default='00:00', max_length=6),
            preserve_default=False,
        ),
    ]
