# Generated by Django 4.1.3 on 2022-11-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muearly', '0003_product_created_date_product_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
