# Generated by Django 4.1.6 on 2023-02-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('url', models.URLField()),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField()),
                ('normal_price', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
                ('discount_type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
